class ShapeBuilderPostgreSQL

  attr_accessor :shape_directory  
  
  def initialize(shape_directory)
    @shape_directory = shape_directory
  end
  
  def build(feature)
    filename = "#{shape_directory}/#{feature.filename}"

    config = Rails.configuration
    database = config.database_configuration[RAILS_ENV]["database"]
    username = config.database_configuration[RAILS_ENV]["username"]
    password = config.database_configuration[RAILS_ENV]["password"]
    
    begin
      # Building shape files using Postgis's pgsql2shp cmd
      result = %x[pgsql2shp -f #{filename} -u #{username} -P #{password} -r #{database} #{feature.tablename}]      
      
      if result.include? 'The DBF file will be created but not the shx or shp files'
        File.delete("#{filename}.dbf")
        throw
      end
    rescue
      raise ArgumentError, "Shape files for #{feature.tablename} could not be generated by pgsql2shp"
    end
  end
  
  def file_extensions
    ['dbf', 'shp', 'shx']
  end
  
end