#! /bin/bash
# chkconfig: 2345 01 10
# description: Starts the geoserver

case "$1" in
  start)
    cd /geoserver/geoserver-2.0.2/bin/
    ./startup.sh &
    ;;
  stop)
    cd /geoserver/geoserver-2.0.2/bin/
    ./shutdown.sh
    ;;
  *)
    echo "Usage: /etc/init.d/geoserver {start|stop}"
    exit 1
    ;;
esac

exit 0
