#! /bin/bash
# chkconfig: 2345 01 09
# description: Starts postgres

case "$1" in
  start)
    su postgres -c "cd /usr/local/pgsql/bin/; ./pg_ctl start -D /usr/local/pgsql/data/"
    exit
    ;;
  stop)
    su postgres -c "cd /usr/local/pgsql/bin/; ./pg_ctl stop"
    exit
    ;;
  *)
    echo "Usage: /etc/init.d/postgres {start|stop}"
    exit 1
    ;;
esac

exit 0
