#! /bin/bash
# chkconfig: 2345 01 10
# description: Starts the WEHub's social network (enginey)

case "$1" in
  start)
    cd /projects/EngineY/
    ./boot.sh
    ;;
  stop)
    ;;
  *)
    echo "Usage: /etc/init.d/wehub-enginey {start|stop}"
    exit 1
    ;;
esac

exit 0
