#! /bin/bash
# chkconfig: 2345 01 10
# description: Starts the WEHub's search app

case "$1" in
  start)
    cd /projects/WEHub/apps/search/
    ./boot.sh
    ;;
  stop)
    ;;
  *)
    echo "Usage: /etc/init.d/wehub-search {start|stop}"
    exit 1
    ;;
esac

exit 0
